### ISSUE TITLE
Renaming the packages

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#126]
In order to avoid confusion, I think we should consider renaming ChildRecordsData and ChildRecordsR to something that makes it transparent that: 

 - One package is about _managing the data_ and is in _python_ (though one might use it without touching any line of python code)
 - One package is about _extracting statistics from the data_ and is in _R_.

So what about:

- childrecords-data-py
- childrecords-stats-r

or something like that ?

What's your opinion @alsonicr @alecristia

**Comment by camiscaff** [comment]
i think it is a great idea!

**Comment by alsonicr** [comment]
To my point of view the more important is that people should know by name they are part of the same project.
For now we can considere each of them use "unique" language, but i will not bet that will be the case forever. There is not python code to produce statistics too. 

R is very often associate with statistic because it is the main function of the language a little be redundant .

I will said ChildRecordsData and ChildRecordsR have the advantage to be more marketable then the proposition.Plus word play ChildRecordsR  / child recorder.

Don't take my argument as too seriouly, I just like the name we have now and i don't really like product with "-", it is always bad marketing and visually don't like it :D.

**Comment by alecristia** [comment]
I don't have a strong opinion; but I can generate one if I'm the deciding vote. I think not: there are 2 votes for changing (LG & CS) and one for staying put (NR). Just to complexify:

- we can imagine the same functions being wrapped in bash or R, which is an argument for not adding py (and for removing R)
- I'm afraid many people will miss the 's' in childrecordS (it's unexpected)
- the package could be used with any long recordings, and very few of the fields in metadata are nonsensical if the recordees are adults (or mice)

**Comment by lucasgautheron** [comment]
Closing because of the lack of consensus, thank you all for your input

**Comment by lucasgautheron** [comment]
What about renaming this repository to `ChildProject`, i.e. the name of the python package?

Indeed, it might be confusing that the repository is not named after the package.
