### ISSUE TITLE
message when getting audio in vandam tutorial

### ISSUE THREAD

**Issue by alecristia** [LAAC-LSCP/ChildProject#190]
`wget https://media.talkbank.org/homebank/Public/VanDam-Daylong/BN32/BN32_010007.mp3 -O recordings/raw/BN32_010007.mp3`

yielded

> dyld: Library not loaded: /usr/local/opt/openssl/lib/libssl.1.0.0.dylib
  Referenced from: /usr/local/bin/wget
  Reason: image not found
Abort trap: 6

in mac mini running catalina 10.15.7

So I checked that I had installed wget with brew (which I already had installed):

```
brew install wget
```
Which I had, so I updated it

```
brew upgrade wget
```
And that fixed the problem.

**Comment by lucasgautheron** [comment]
What version of the tutorial are you referring to ?
The latest does not rely on wget but curl instead, since mac does not have wget by default (it's the other way around on linux, but we figured it we should better make mac users life easier) 

https://childproject.readthedocs.io/en/latest/vandam.html
