### ISSUE TITLE
Re-imported annotations

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#412]
In light of this, I wondered what was the effect on re-importing annotations on the index of annotations.
Intuitively, if redundant entries are not allowed than the entry to be saved should be the most recent one (with the highest value of "imported_at")

Although, according to the following line of code, it does not seem to be the case? Or at least it is unclear that it would be the case. See: https://github.com/LAAC-LSCP/ChildProject/blob/32e1c813349d27be649fa1d8c0aef41f5027dfa4/ChildProject/annotations.py#L1075

What is the present behavior?

Thank you for the help!

**Comment by LoannPeurey** [comment]
I had not taken a deep look into this before (probably as we did not encounter cases re-importing) but it indeed looks like this is a problem at the moment.

The current system allows redundant entries, so that can result in multiple lines referring to the same annotation file.
The lines are added without checking for duplicates in `import_annotations`:
https://github.com/LAAC-LSCP/ChildProject/blob/32e1c813349d27be649fa1d8c0aef41f5027dfa4/ChildProject/annotations.py#L606

Evenly concerning is the section you are referring to, which is in the `merge_sets` method. If that function does remove duplicates when the rest of the code allows them, this can lead to `merge_sets` changing part of the index we don't expect to be changed by it.

So I think we should review the code to make sure duplicates are not allowed anymore. I am thinking that `import-annotations` should by default refuse to import lines that already exists and that we should have an optionnal argument to override existing lines to be reimported.
