### ISSUE TITLE
Sampler parameters

### ISSUE THREAD

**Issue by lucasgautheron** [LAAC-LSCP/ChildProject#89]
List all possible parameters for the samplers

**Comment by alecristia** [comment]
Examples: 

- already implemented in your zooniverse pipeline stretch: pull X random vocs by CHN/CHI
- another options for zooniverse: 
    - pull X random vocs by FAN/FEM (or any other speaker)
    - pull all the CHN vocs in a region where there are lots of CHN ("high volubility")
    - pull all the FAN vocs in a region where there are lots of FAN ("high volubility")
    - pull all the CHN vocs in a region where there are lots of CHN-FAN alternations/turns ("high exchanges")

- eaf template producer (notice the version): https://github.com/aclew/EAF_builder_scripts/tree/Second-Version
    - already has: random, periodic, high volubility FAN & CHN, high exchanges (using LENA's conversational turn count)

- In this paper, they use a method of classifying something in context, similar to one of the annotation tasks I mentioned: Bergelson, E., Casillas, M., Soderstrom, M., Seidl, A., Warlaumont, A. S., & Amatuni, A. (2019). What do north American babies hear? A large‐scale cross‐corpus analysis. Developmental science, 22(1), e12724.
their code is on github, let me know if you don't find it

- In this paper, they use a method of classifying 30s samples, to bear in mind since many of my colleagues do similar things -- code on github: Cychosz, M., Villanueva, A., & Weisleder, A. (2020). Efficient estimation of children's language exposure in two bilingual communities.
